import { FLOW_OWNED_REQUEST_HEADERS } from '../../shared/businessContext'
import { isSimpleMethod } from '../../shared/types'
import { TypedEnv } from '../types'
import { getAllowedOrigin } from '../urlMatching'
import { removeHeaderValue } from '../utils/headers'
import { fetchOrigin } from '../utils/origin'
import { copyRequest, setCorsHeadersForInstrumentation } from '../utils/request'
import { copyResponseWithNewHeaders } from '../utils/response'

export type HandleProtectedApiOptionsParams = {
  request: Request
  env: TypedEnv
}

export async function handleProtectedApiOptionsCall({
  request,
  env,
}: HandleProtectedApiOptionsParams): Promise<Response> {
  // Check if the OPTIONS request was caused by the addition
  // of Flow-owned headers to the instrumented request
  const accessControlRequestHeaders = request.headers.get('Access-Control-Request-Headers')
  const accessControlRequestMethod = request.headers.get('Access-Control-Request-Method')
  const requestedHeaders = splitAccessControlRequestHeaders(accessControlRequestHeaders)

  if (
    isOnlyFlowOwnedHeaders(requestedHeaders) &&
    accessControlRequestMethod &&
    isSimpleMethod(accessControlRequestMethod)
  ) {
    const allowedOrigin = getAllowedOrigin(request, env)
    if (allowedOrigin) {
      // Self-handle when the preflight exists only because of Flow-owned headers
      // (fp-data / fp-tag / fp-linked-id). Note: a customer who sets only fp-tag
      // without instrumentation would also hit this path — spike tradeoff vs
      // forwarding to an origin that may not allow those headers.
      console.debug('Handled instrumentation-triggered preflight request without forwarding to origin')
      return new Response(null, {
        status: 204,
        headers: {
          'Access-Control-Allow-Origin': allowedOrigin,
          'Access-Control-Allow-Headers': requestedHeaders.join(','),
          'Access-Control-Allow-Methods': accessControlRequestMethod,
          'Access-Control-Allow-Credentials': 'true',
        },
      })
    }

    // Reaching this point indicates that the worker received a request that
    // appears to have been generated by an instrumentation page. However, the
    // origin of the request is not one of the configured identification pages.
    //
    // This likely indicates an issue with the setup such as a different Flow
    // worker instance instrumenting a page that calls a protected API handled
    // by this Flow worker.
    //
    // Attempt to fail gracefully and let the origin handle this error case.
  }

  if (requestedHeaders.some((header) => isFlowOwnedRequestHeader(header))) {
    // Flow-owned headers need to be removed from the forwarded request to
    // avoid unexpected results from the origin.

    const originRequestHeaders = new Headers(request.headers)

    for (const header of FLOW_OWNED_REQUEST_HEADERS) {
      removeHeaderValue(originRequestHeaders, 'Access-Control-Request-Headers', header)
    }

    const originRequest = copyRequest({
      request,
      init: {
        headers: originRequestHeaders,
      },
    })

    const originResponse = await fetchOrigin(originRequest)

    const originResponseHeaders = new Headers(originResponse.headers)

    setCorsHeadersForInstrumentation(request, originResponseHeaders)

    return copyResponseWithNewHeaders(originResponse, originResponseHeaders)
  }

  // The OPTIONS request matches a protected API but the request is not being
  // instrumented so forward the OPTIONS request to the origin. Protection
  // logic will be applied to the actual request
  return fetchOrigin(request)
}

function splitAccessControlRequestHeaders(value: string | null): string[] {
  if (!value) {
    return []
  }
  return value
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
}

function isFlowOwnedRequestHeader(name: string): boolean {
  const lower = name.toLowerCase()
  return FLOW_OWNED_REQUEST_HEADERS.some((header) => header.toLowerCase() === lower)
}

function isOnlyFlowOwnedHeaders(headers: string[]): boolean {
  return headers.length > 0 && headers.every((header) => isFlowOwnedRequestHeader(header))
}
